---
- name: SETUP BIG-IP
  hosts: localhost
  vars_prompt:
    - name: username
      prompt: Please provide the username
    - name: password
      prompt: password
    - name: chg
    
  tasks:
      - name: Create UCS File
        bigip_ucs_fetch:
          src: BKP_'{{ chg }}'.ucs
          only_create_file: true
          provider:
            server: 192.168.117.2
            user: '{{ username }}'
            password: '{{ password }}'
            validate_certs: no
        delegate_to: localhost

      - name: Download UCS File
        bigip_ucs_fetch:
          src: teste_backup.ucs
          dest: /Backups/BKP_'{{ chg }}'.ucs
          provider:
            server: 192.168.117.2
            user: '{{ username }}'
            password: '{{ password }}'
            validate_certs: no
        delegate_to: localhost
