---
- name: SETUP BIG-IP
  hosts: localhost
  vars_prompt:
    - name: username
      prompt: Please provide the username
      
    - name: password
      prompt: password
      
    - name: chg
      prompt: Change Number
    
  tasks:
      - name: Create UCS File
        bigip_ucs_fetch:
          src: BKP_{{ chg }}_{{ ansible_date_time }}.ucs
          only_create_file: true
          provider:
            server: 192.168.117.2
            user: '{{ username }}'
            password: '{{ password }}'
            validate_certs: no
        delegate_to: localhost

      - name: Download UCS File
        bigip_ucs_fetch:
          src: BKP_{{ chg }}_{{ ansible_date_time }}.ucs
          dest: /Backups/BKP_{{ chg }}_{{ ansible_date_time }}.ucs
          provider:
            server: 192.168.117.2
            user: '{{ username }}'
            password: '{{ password }}'
            validate_certs: no
        delegate_to: localhost
